### ISSUE TITLE
Version ruby, rails chưa đồng bộ và lỗi gặp phải khi start project bằng latest version

### ISSUE THREAD

**Issue by gintran** [vfa-tranhv/vfa-workshop-ruby-on-rails#1]
Đây là feedback từ buổi 1 của workshop:

- [x] Version cài đặt chưa ổn định, cần đồng bộ
- [x] Khi em tự thử với version mới nhất ruby-2.6.3, rails-6.0.0 thì bị lỗi webpack không tự động build
  cách xử lý: cài đặt webpack bằng câu lệnh `rails webpacker:install` và `rails s` lại thì OK

**Comment by vfa-tranhv** [comment]
Cảm ơn Gin nhé, mình sẽ update dùng ruby và rails mới nhất cho xịn :D

**Comment by gintran** [comment]
Issue này đã được fix nên em close nha
